import { SemanticPlan, ComplexityResult, ComplexityLevel } from "./types";

/**
 * Interface that represents the context metadata generated by the RAG Engine (Graph Grounding)
 * Same as exported in schema-engine.ts, repeated here for type isolation if needed, or we could import it.
 */
export interface RAGContextMetadata {
  routerTables: string[];
  seedTables: string[];
  expandedTables: string[];
  finalAllowedTables: string[];
}

/**
 * Deterministically classifies query complexity based on the Semantic Plan
 * and the Grounded Context (Dictionary/Graph resolution).
 */
export function classifyQueryComplexity(
  plan: SemanticPlan,
  context: RAGContextMetadata
): ComplexityResult {
  const reasons: string[] = [];
  let score = 0; // Internal heuristic score, not exposed as a magic number

  // 1. Analyze grounded context (topology)
  const numTables = context.finalAllowedTables.length;
  const numExpanded = context.expandedTables.length;
  
  if (numTables >= 4) {
    reasons.push(`${numTables} tabelas conectadas`);
    score += 2;
  }
  
  if (numExpanded >= 2) {
    reasons.push(`caminho de relacionamento indireto (${numExpanded} tabelas intermediárias)`);
    score += 3;
  }

  // 2. Analyze Semantic Plan (intent)
  const numDomains = plan.domains?.length || 0;
  if (numDomains > 1) {
    reasons.push(`múltiplos domínios envolvidos (${numDomains})`);
    score += 3;
  }

  const hasAggr = plan.aggregations && plan.aggregations.length > 0;
  const hasGroup = plan.grouping && plan.grouping.length > 0;
  if (hasAggr || hasGroup) {
    reasons.push(`agregações ou agrupamento`);
    score += 3;
  }

  const hasTemporal = plan.temporalRequirements && plan.temporalRequirements.length > 0;
  if (hasTemporal) {
    reasons.push(`requisito de comparação temporal`);
    score += 3;
  }

  const hasSubquery = plan.operations && (plan.operations.includes("subquery") || plan.operations.includes("cte"));
  if (hasSubquery) {
    reasons.push(`requer CTE ou subquery`);
    score += 4;
  }

  // 3. Determine Final Level based on score
  let level: ComplexityLevel = "simple";
  if (score >= 8) {
    level = "complex";
  } else if (score >= 4) {
    level = "moderate";
  }

  return {
    level,
    reasons
  };
}
